{"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDILogLevel"}],"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@E@LCMIDILogLevel","role":"symbol","modules":[{"name":"LaunchControl"}],"navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevel"}],"title":"LCMIDILogLevel"},"kind":"symbol","identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl"]]},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/error","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/fatal","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/info","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/warning"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/Equatable-Implementations","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/launchcontrol\/lcmidiloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmidiloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.soundform.LaunchControl\/s15BitwiseCopyableP","doc:\/\/com.soundform.LaunchControl\/SQ","doc:\/\/com.soundform.LaunchControl\/SH","doc:\/\/com.soundform.LaunchControl\/SY","doc:\/\/com.soundform.LaunchControl\/s8SendableP"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDILogLevel","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.soundform.LaunchControl/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.soundform.LaunchControl\/s8SendableP","title":"Swift.Sendable"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/error":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/error","title":"LCMIDILogLevel.error","abstract":[],"url":"\/documentation\/launchcontrol\/lcmidiloglevel\/error","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDILogLevelError","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/fatal":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/fatal","title":"LCMIDILogLevel.fatal","abstract":[],"url":"\/documentation\/launchcontrol\/lcmidiloglevel\/fatal","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fatal"}],"navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevelFatal"}]},"doc://com.soundform.LaunchControl/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.soundform.LaunchControl\/s15BitwiseCopyableP"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/warning":{"navigatorTitle":[{"text":"LCMIDILogLevelWarning","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/warning","role":"symbol","abstract":[],"kind":"symbol","title":"LCMIDILogLevel.warning","url":"\/documentation\/launchcontrol\/lcmidiloglevel\/warning","type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/init(rawValue:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/launchcontrol\/lcmidiloglevel\/init(rawvalue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel":{"url":"\/documentation\/launchcontrol\/lcmidiloglevel","title":"LCMIDILogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDILogLevel"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevel"}],"role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel","abstract":[],"type":"topic"},"doc://com.soundform.LaunchControl/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.soundform.LaunchControl\/SQ","type":"unresolvable"},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","url":"\/documentation\/launchcontrol\/lcmidiloglevel\/equatable-implementations"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/info":{"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/info","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"url":"\/documentation\/launchcontrol\/lcmidiloglevel\/info","title":"LCMIDILogLevel.info","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevelInfo"}]},"doc://com.soundform.LaunchControl/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.soundform.LaunchControl\/SH","type":"unresolvable"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/launchcontrol\/lcmidiloglevel\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup"},"doc://com.soundform.LaunchControl/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.soundform.LaunchControl\/SY","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"LCMIDILogLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LCMIDILogLevel"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"LCMIDILogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/error","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/fatal","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/info","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/warning"],"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDILogLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1error\/title","value":"LCMIDILogLevelError","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1error\/fragments","value":[{"text":"LCMIDILogLevelError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1fatal\/title","value":"LCMIDILogLevelFatal","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1fatal\/fragments","value":[{"text":"LCMIDILogLevelFatal","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1warning\/title","value":"LCMIDILogLevelWarning","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1warning\/fragments","value":[{"kind":"identifier","text":"LCMIDILogLevelWarning"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/title","value":"LCMIDILogLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/fragments","value":[{"kind":"identifier","text":"LCMIDILogLevel"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/navigatorTitle","value":[{"text":"LCMIDILogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1info\/title","value":"LCMIDILogLevelInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1info\/fragments","value":[{"text":"LCMIDILogLevelInfo","kind":"identifier"}],"op":"replace"}]}]}