{"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/init(clientName:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/connectedDevices","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/maxMIDIPacketDataSize"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/allMIDIDeviceNames()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/deviceName(forEndpoint:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/disableDebugLogging()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/index(ofOutputDeviceNamed:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/isDeviceAvailable(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/outputEndpoint(forDeviceNamed:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/rescanDevices()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/resetMIDIClient()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toDeviceNamed:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toEndpoint:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDeviceListDidChangeHandler(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDispatchQueue(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setInputHandler(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setMaxMIDIPacketDataSize(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/start()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/stop()"]}],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"},"sections":[],"metadata":{"externalID":"c:objc(cs)LCMIDIDeviceManager","roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"LaunchControl"}],"title":"LCMIDIDeviceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDIDeviceManager"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"abstract":[{"type":"text","text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager"]}],"seeAlsoSections":[{"title":"Getting Started","anchor":"Getting-Started","generated":true,"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.soundform.LaunchControl\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.soundform.LaunchControl\/objc(pl)NSObject","doc:\/\/com.soundform.LaunchControl\/s7CVarArgP","doc:\/\/com.soundform.LaunchControl\/s28CustomDebugStringConvertibleP","doc:\/\/com.soundform.LaunchControl\/s23CustomStringConvertibleP","doc:\/\/com.soundform.LaunchControl\/SQ","doc:\/\/com.soundform.LaunchControl\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDIDeviceManager"}]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"codeVoice","code":"LCMIDIDeviceManager"},{"type":"text","text":" provides a centralized interface for interacting with CoreMIDI endpoints."},{"type":"text","text":" "},{"type":"text","text":"It supports device enumeration, name-to-endpoint resolution, inbound message reception, and outbound data transmission."},{"type":"text","text":" "},{"type":"text","text":"This manager abstracts the CoreMIDI C APIs into an Objective-C interface suitable for both Objective-C and Swift applications."}],"type":"paragraph"}]}],"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/index(ofOutputDeviceNamed:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/index(ofOutputDeviceNamed:)","abstract":[{"text":"Returns the index of a named output device within the internal output device list.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfOutputDeviceNamed:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofOutputDeviceNamed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"index(ofOutputDeviceNamed:)","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/index(ofoutputdevicenamed:)"},"doc://com.soundform.LaunchControl/SH":{"type":"unresolvable","identifier":"doc:\/\/com.soundform.LaunchControl\/SH","title":"Swift.Hashable"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/init(clientName:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithClientName:"}],"abstract":[{"type":"text","text":"Creates and configures a new instance of the MIDI device manager with a client name to register with CoreMIDI."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(clientName:)","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/init(clientname:)","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/init(clientName:)","kind":"symbol","type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/allMIDIDeviceNames()":{"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/allMIDIDeviceNames()","role":"symbol","abstract":[{"text":"Retrieves a combined list of all known MIDI device names, including both input and output endpoints.","type":"text"}],"title":"allMIDIDeviceNames()","type":"topic","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/allmididevicenames()","navigatorTitle":[{"text":"allMIDIDeviceNames","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allMIDIDeviceNames","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/start()":{"title":"start()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/start()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start"}],"abstract":[{"type":"text","text":"Initializes the internal CoreMIDI client and allocates input and output ports."}],"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/start()","role":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/send(_:toDeviceNamed:)":{"role":"symbol","type":"topic","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/send(_:todevicenamed:)","navigatorTitle":[{"kind":"identifier","text":"sendData:toDeviceNamed:"}],"kind":"symbol","title":"send(_:toDeviceNamed:)","abstract":[{"text":"Sends a MIDI message to a connected output device identified by its name.","type":"text"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toDeviceNamed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toDeviceNamed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/setDeviceListDidChangeHandler(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setDeviceListDidChangeHandler:"}],"type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDeviceListDidChangeHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDeviceListDidChangeHandler"},{"kind":"text","text":"(((["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/setdevicelistdidchangehandler(_:)","kind":"symbol","abstract":[{"type":"text","text":"Registers a block to be executed when the list of connected devices changes due to system notifications or manual rescan."}],"role":"symbol","title":"setDeviceListDidChangeHandler(_:)"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/maxMIDIPacketDataSize":{"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/maxmidipacketdatasize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMIDIPacketDataSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"maxMIDIPacketDataSize","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/maxMIDIPacketDataSize","abstract":[{"type":"text","text":"Maximum allowed size in bytes for a single MIDI packet data message."},{"type":"text","text":" "},{"type":"text","text":"Messages larger than this will be rejected and logged as warnings."},{"type":"text","text":" "},{"type":"text","text":"Default is 4096 bytes."}],"navigatorTitle":[{"kind":"identifier","text":"maxMIDIPacketDataSize"}]},"doc://com.soundform.LaunchControl/SQ":{"identifier":"doc:\/\/com.soundform.LaunchControl\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.soundform.LaunchControl/objc(pl)NSObject":{"identifier":"doc:\/\/com.soundform.LaunchControl\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/setDispatchQueue(_:)":{"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/setdispatchqueue(_:)","navigatorTitle":[{"kind":"identifier","text":"setDispatchQueue:"}],"type":"topic","title":"setDispatchQueue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDispatchQueue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDispatchQueue(_:)","role":"symbol","abstract":[{"type":"text","text":"Specifies the dispatch queue on which the input handler block should execute."}],"kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/disableDebugLogging()":{"navigatorTitle":[{"kind":"identifier","text":"disableDebugLogging"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableDebugLogging"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/disableDebugLogging()","type":"topic","abstract":[{"type":"text","text":"Disables debug output previously enabled with "},{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"disableDebugLogging()","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/disabledebuglogging()","role":"symbol"},"doc://com.soundform.LaunchControl/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.soundform.LaunchControl\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/send(_:toEndpoint:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toEndpoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@MIDIEndpointRef","text":"MIDIEndpointRef","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"sendData:toEndpoint:","kind":"identifier"}],"title":"send(_:toEndpoint:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toEndpoint:)","abstract":[{"text":"Sends a MIDI message directly to the specified CoreMIDI output endpoint.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/send(_:toendpoint:)"},"doc://com.soundform.LaunchControl/objc(cs)NSObject":{"identifier":"doc:\/\/com.soundform.LaunchControl\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.soundform.LaunchControl/s7CVarArgP":{"identifier":"doc:\/\/com.soundform.LaunchControl\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/resetMIDIClient()":{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/resetMIDIClient()","abstract":[{"text":"Resets the internal MIDI client and ports, reinitializing them.","type":"text"},{"text":" ","type":"text"},{"text":"Useful for recovering from errors or device changes without restarting the app.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"resetMIDIClient","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetMIDIClient","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/resetmidiclient()","title":"resetMIDIClient()","type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/connectedDevices":{"abstract":[{"type":"text","text":"An array of connected and available output device names currently visible to the system."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectedDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/connecteddevices","title":"connectedDevices","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectedDevices"}],"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/connectedDevices"},"doc://com.soundform.LaunchControl/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.soundform.LaunchControl\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/stop()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stop"}],"title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Tears down the CoreMIDI client and releases all allocated ports and endpoint references."}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/stop()","kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/stop()","type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/midi":{"kind":"article","abstract":[{"type":"text","text":"A standard protocol for communication between electronic musical instruments and devices."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi","type":"topic","url":"\/documentation\/launchcontrol\/midi","role":"article","title":"Understanding MIDI Protocol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/setInputHandler(_:)":{"abstract":[{"type":"text","text":"Assigns a handler block to receive incoming MIDI messages from all connected input sources."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setInputHandler(_:)","title":"setInputHandler(_:)","kind":"symbol","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/setinputhandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInputHandler"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setInputHandler:"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/deviceName(forEndpoint:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forEndpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MIDIEndpointRef","text":"MIDIEndpointRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceNameForEndpoint:"}],"role":"symbol","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/devicename(forendpoint:)","kind":"symbol","title":"deviceName(forEndpoint:)","abstract":[{"text":"Resolves the device name associated with a given MIDI endpoint reference.","type":"text"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/deviceName(forEndpoint:)"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/enableDebugLogging()":{"role":"symbol","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/enabledebuglogging()","title":"enableDebugLogging()","navigatorTitle":[{"kind":"identifier","text":"enableDebugLogging"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDebugLogging"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","kind":"symbol","abstract":[{"type":"text","text":"Enables debug output for MIDI message transmission and reception to assist with development and troubleshooting."}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/outputEndpoint(forDeviceNamed:)":{"role":"symbol","kind":"symbol","title":"outputEndpoint(forDeviceNamed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputEndpoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDeviceNamed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef"}],"navigatorTitle":[{"kind":"identifier","text":"outputEndpointForDeviceNamed:"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/outputEndpoint(forDeviceNamed:)","type":"topic","abstract":[{"type":"text","text":"Resolves the specified output device name to a "},{"code":"MIDIEndpointRef","type":"codeVoice"},{"type":"text","text":" that can be used for direct transmission."}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/outputendpoint(fordevicenamed:)"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/rescanDevices()":{"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/rescandevices()","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/rescanDevices()","title":"rescanDevices()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rescanDevices"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rescanDevices"}],"abstract":[{"type":"text","text":"Manually initiates a device rescan to refresh the list of available endpoints."}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/setMaxMIDIPacketDataSize(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setMaxMIDIPacketDataSize:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the maximum allowed size in bytes for a single MIDI packet data message."},{"type":"text","text":" "},{"type":"text","text":"Messages larger than this will be rejected and logged as warnings."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setMaxMIDIPacketDataSize(_:)","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/setmaxmidipacketdatasize(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxMIDIPacketDataSize"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"setMaxMIDIPacketDataSize(_:)","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/isDeviceAvailable(_:)":{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/isDeviceAvailable(_:)","title":"isDeviceAvailable(_:)","kind":"symbol","type":"topic","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/isdeviceavailable(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeviceAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isDeviceAvailable:"}],"abstract":[{"type":"text","text":"Checks whether a specific output device is currently available by name."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LCMIDIDeviceManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/connectedDevices","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/maxMIDIPacketDataSize"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/allMIDIDeviceNames()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/deviceName(forEndpoint:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/disableDebugLogging()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/index(ofOutputDeviceNamed:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/init(clientName:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/isDeviceAvailable(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/outputEndpoint(forDeviceNamed:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/rescanDevices()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/resetMIDIClient()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toDeviceNamed:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toEndpoint:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDeviceListDidChangeHandler(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDispatchQueue(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setInputHandler(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setMaxMIDIPacketDataSize(_:)","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/start()","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/stop()"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.soundform.LaunchControl\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi"],"anchor":"Getting-Started","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDIDeviceManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1index(ofOutputDeviceNamed:)\/title","value":"indexOfOutputDeviceNamed:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1index(ofOutputDeviceNamed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfOutputDeviceNamed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1init(clientName:)\/title","value":"initWithClientName:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1init(clientName:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithClientName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1allMIDIDeviceNames()\/title","value":"allMIDIDeviceNames"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1allMIDIDeviceNames()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"allMIDIDeviceNames","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1start()\/title","value":"start"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1send(_:toDeviceNamed:)\/title","value":"sendData:toDeviceNamed:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1send(_:toDeviceNamed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendData:toDeviceNamed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setDeviceListDidChangeHandler(_:)\/title","value":"setDeviceListDidChangeHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setDeviceListDidChangeHandler(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDeviceListDidChangeHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1maxMIDIPacketDataSize\/title","value":"maxMIDIPacketDataSize"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1maxMIDIPacketDataSize\/fragments","value":[{"kind":"identifier","text":"maxMIDIPacketDataSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setDispatchQueue(_:)\/title","value":"setDispatchQueue:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setDispatchQueue(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDispatchQueue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1disableDebugLogging()\/title","value":"disableDebugLogging"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1disableDebugLogging()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disableDebugLogging","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1send(_:toEndpoint:)\/title","value":"sendData:toEndpoint:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1send(_:toEndpoint:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendData:toEndpoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1resetMIDIClient()\/title","value":"resetMIDIClient"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1resetMIDIClient()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetMIDIClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1connectedDevices\/title","value":"connectedDevices"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1connectedDevices\/fragments","value":[{"text":"connectedDevices","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1stop()\/title","value":"stop"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1stop()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setInputHandler(_:)\/title","value":"setInputHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setInputHandler(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setInputHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1deviceName(forEndpoint:)\/title","value":"deviceNameForEndpoint:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1deviceName(forEndpoint:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deviceNameForEndpoint:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1enableDebugLogging()\/title","value":"enableDebugLogging"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1enableDebugLogging()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableDebugLogging","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1outputEndpoint(forDeviceNamed:)\/title","value":"outputEndpointForDeviceNamed:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1outputEndpoint(forDeviceNamed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"outputEndpointForDeviceNamed:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1rescanDevices()\/title","value":"rescanDevices"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1rescanDevices()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rescanDevices","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setMaxMIDIPacketDataSize(_:)\/title","value":"setMaxMIDIPacketDataSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setMaxMIDIPacketDataSize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMaxMIDIPacketDataSize:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1isDeviceAvailable(_:)\/title","value":"isDeviceAvailable:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1isDeviceAvailable(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isDeviceAvailable:","kind":"identifier"}]}]}]}