{"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"LaunchControl"}],"title":"Understanding MIDI Protocol"},"sections":[],"abstract":[{"type":"text","text":"A standard protocol for communication between electronic musical instruments and devices."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Getting Started","anchor":"Getting-Started","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"],"generated":true}],"primaryContentSections":[{"content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"MIDI (Musical Instrument Digital Interface) is a technical standard that enables communication between"},{"type":"text","text":" "},{"type":"text","text":"electronic musical instruments, computers, and other related devices. It allows these devices to send and"},{"type":"text","text":" "},{"type":"text","text":"receive messages that control musical performance, such as note information, control changes, and timing"},{"type":"text","text":" "},{"type":"text","text":"signals. Since its introduction in the early 1980s, MIDI has become a foundational protocol in music"},{"type":"text","text":" "},{"type":"text","text":"production, live performance, and digital audio workflows."}]},{"type":"paragraph","inlineContent":[{"text":"MIDI does not transmit audio itself but rather data that represents musical events and controls, making it","type":"text"},{"text":" ","type":"text"},{"text":"highly efficient for real-time performance and flexible control across various devices and software.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"midi-connectivity.png"},{"type":"text","text":" "},{"type":"emphasis","inlineContent":[{"text":"Figure 1: Bidirectional MIDI communication between device and host.","type":"text"}]}]},{"type":"paragraph","inlineContent":[{"text":"MIDI devices, such as keyboards or controllers, communicate with host computers or synthesizers by sending","type":"text"},{"text":" ","type":"text"},{"text":"MIDI messages that represent musical events or control changes. This communication is bidirectional: the","type":"text"},{"text":" ","type":"text"},{"text":"device sends messages to the host to trigger notes or control parameters, while the host can send messages","type":"text"},{"text":" ","type":"text"},{"text":"back to the device to update its state—for example, lighting up LEDs on a controller or providing other forms","type":"text"},{"text":" ","type":"text"},{"text":"of feedback. The diagram below illustrates this typical connection flow, showing how data moves between the","type":"text"},{"text":" ","type":"text"},{"text":"MIDI device and the host in both directions.","type":"text"}]},{"anchor":"MIDI-Message-Structure","text":"MIDI Message Structure","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"MIDI messages are the building blocks of communication between devices. Each message consists of one"},{"type":"text","text":" "},{"type":"text","text":"status byte followed by one or two data bytes. The status byte indicates the type of message and the MIDI"},{"type":"text","text":" "},{"type":"text","text":"channel it belongs to, while the data bytes provide details such as note number or velocity."}]},{"anchor":"Message-Format","text":"Message Format","type":"heading","level":4},{"alignments":["center","center","center"],"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Byte Type","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Example Value"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Status Byte"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Identifies message type and channel"}]}],[{"type":"paragraph","inlineContent":[{"text":"0x90 (Note On, Ch. 1)","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Data Byte 1","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Usually note number or controller ID"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"0x3C (Middle C note)"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data Byte 2"}]}],[{"type":"paragraph","inlineContent":[{"text":"Usually velocity or controller value","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"0x40 (velocity 64)","type":"text"}]}]]]},{"type":"paragraph","inlineContent":[{"text":"Each MIDI channel ranges from 1 to 16, and the status byte encodes this in its lower nibble (half byte).","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"midi-message-structure.png","type":"image"},{"text":" ","type":"text"},{"inlineContent":[{"text":"Figure 2: MIDI message byte format showing status and data bytes.","type":"text"}],"type":"emphasis"}]},{"level":4,"text":"Common MIDI Messages","type":"heading","anchor":"Common-MIDI-Messages"},{"inlineContent":[{"type":"text","text":"MIDI communication relies on several fundamental message types that enable devices to exchange musical"},{"type":"text","text":" "},{"type":"text","text":"instructions. The Note On message tells a device to begin playing a note and includes the note’s pitch"},{"type":"text","text":" "},{"type":"text","text":"(for example, middle C, 0x3C) and velocity, which reflects how forcefully the note is played. Its counterpart,"},{"type":"text","text":" "},{"type":"text","text":"the Note Off message, signals the device to stop playing that note, typically with a velocity of zero. The"},{"type":"text","text":" "},{"type":"text","text":"status byte for Note On on channel 1 is 0x90, and for Note Off, it’s 0x80."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Control Change (CC) messages modify parameters like volume, pan, or modulation. Each message carries a"},{"type":"text","text":" "},{"type":"text","text":"controller number identifying the parameter and a value setting its level—controller 7 (0x07) commonly adjusts"},{"type":"text","text":" "},{"type":"text","text":"volume. The status byte for Control Change on channel 1 is 0xB0."}],"type":"paragraph"},{"inlineContent":[{"text":"The Program Change message switches the instrument or sound patch on the device. It contains a single data","type":"text"},{"text":" ","type":"text"},{"text":"byte representing the program number to select the desired sound. The status byte for Program Change on","type":"text"},{"text":" ","type":"text"},{"text":"channel 1 is 0xC0.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Finally, Pitch Bend messages enable smooth, continuous pitch variations by sending a 14-bit value split over","type":"text"},{"text":" ","type":"text"},{"text":"two data bytes (least and most significant). The status byte for Pitch Bend on channel 1 is 0xE0. This allows","type":"text"},{"text":" ","type":"text"},{"text":"expressive effects such as vibrato and pitch slides.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Together, these core messages form the basis of MIDI’s ability to communicate detailed musical commands","type":"text"},{"text":" ","type":"text"},{"text":"between instruments, controllers, and software.","type":"text"}],"type":"paragraph"},{"level":3,"text":"Section header","type":"heading","anchor":"Section-header"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl"]]},"variants":[{"paths":["\/documentation\/launchcontrol\/midi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/midi"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"midi-connectivity.png":{"type":"image","alt":"Bidirectional MIDI communication between device and host","variants":[{"url":"\/images\/com.soundform.LaunchControl\/midi-connectivity@1x~dark.png","traits":["1x","dark"]}],"identifier":"midi-connectivity.png"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"midi-message-structure.png":{"type":"image","alt":"Message Structure","variants":[{"url":"\/images\/com.soundform.LaunchControl\/midi-message-structure@1x~dark.png","traits":["1x","dark"]}],"identifier":"midi-message-structure.png"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Getting Started","anchor":"Getting-Started","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}