{"kind":"symbol","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"sections":[],"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Getting-Started","title":"Getting Started","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi"]},{"anchor":"Articles","title":"Articles","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/launchcontrolplayground","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midigridanimator"],"generated":true},{"anchor":"Protocols","title":"Protocols","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCLaunchpadDevice"],"generated":true},{"anchor":"Functions","title":"Functions","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIWriteLog(_:_:_:_:_:)"],"generated":true},{"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel"],"generated":true},{"anchor":"Extended-Modules","title":"Extended Modules","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/Foundation"],"generated":true}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"LaunchControl is a CoreMIDI-based framework for managing communication between your app and MIDI hardware, with specific support for Novation Launchpads and similar devices.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"It provides a streamlined interface for discovering endpoints, establishing connections, and sending or receiving MIDI messages—all with performance and reliability suitable for real-time, latency-sensitive environments.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Designed with both developers and performers in mind, LaunchControl includes:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"Automatic discovery of MIDI input and output devices","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Efficient message transmission with packet size validation and structured logging","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Live monitoring of connection changes, enabling dynamic responses to device attachment or removal","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Integrated support for displaying hex dumps for inspection and debugging"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"LaunchControl abstracts the complexities of CoreMIDI, helping you focus on your app’s creative functionality.","type":"text"}]},{"anchor":"Dive-into-featured-sample-apps","text":"Dive into featured sample apps","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Explore how LaunchControl integrates into real-world scenarios with sample apps that demonstrate device interaction, grid control, velocity input handling, and visual feedback."}]},{"items":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midigridanimator","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/launchcontrolplayground"],"style":"detailedGrid","type":"links"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"platforms":[{"name":"macOS","beta":false,"introducedAt":"26.0"},{"name":"Swift","beta":false,"introducedAt":"6.2"}],"title":"LaunchControl","symbolKind":"module","modules":[{"name":"LaunchControl"}],"externalID":"LaunchControl","roleHeading":"Framework","role":"collection"},"hierarchy":{"paths":[[]]},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/midigridanimator":{"kind":"article","images":[{"identifier":"Midi-Grid-Animator-Hero.png","type":"card"}],"title":"Midi Grid Animator","type":"topic","abstract":[{"type":"text","text":"Real-time Launchpad LED animation and input using LaunchControl."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midigridanimator","role":"sampleCode","url":"\/documentation\/launchcontrol\/midigridanimator"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LaunchControlVersionString":{"fragments":[{"kind":"identifier","text":"LaunchControlVersionString"}],"type":"topic","abstract":[{"type":"text","text":"Project version string for LaunchControl."}],"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LaunchControlVersionString","title":"LaunchControlVersionString","url":"\/documentation\/launchcontrol\/launchcontrolversionstring","role":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/Foundation":{"kind":"symbol","abstract":[],"title":"Foundation","type":"topic","url":"\/documentation\/launchcontrol\/foundation","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/Foundation","role":"collection"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/midi":{"kind":"article","abstract":[{"type":"text","text":"A standard protocol for communication between electronic musical instruments and devices."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi","type":"topic","url":"\/documentation\/launchcontrol\/midi","role":"article","title":"Understanding MIDI Protocol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel":{"url":"\/documentation\/launchcontrol\/lcmidiloglevel","title":"LCMIDILogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDILogLevel"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevel"}],"role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel","abstract":[],"type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDI_LOG":{"fragments":[{"kind":"identifier","text":"LCMIDI_LOG"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDI_LOG","url":"\/documentation\/launchcontrol\/lcmidi_log","title":"LCMIDI_LOG","role":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCLaunchpadDevice":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCLaunchpadDevice","kind":"identifier"}],"abstract":[],"url":"\/documentation\/launchcontrol\/lclaunchpaddevice","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCLaunchpadDevice","title":"LCLaunchpadDevice","role":"symbol","navigatorTitle":[{"text":"LCLaunchpadDevice","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIWriteLog(_:_:_:_:_:)":{"type":"topic","title":"LCMIDIWriteLog(_:_:_:_:_:)","url":"\/documentation\/launchcontrol\/lcmidiwritelog(_:_:_:_:_:)","abstract":[{"type":"text","text":"Writes a log message with specified level, file, line, and function context."},{"type":"text","text":" "},{"type":"text","text":"Use the provided macro "},{"type":"codeVoice","code":"LCMIDI_LOG"},{"type":"text","text":" for convenient calls."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIWriteLog(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDIWriteLog"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@LCMIDILogLevel","text":"LCMIDILogLevel"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"text":"LCMIDIWriteLog","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/launchcontrolplayground":{"images":[{"type":"card","identifier":"Midi-Grid-Animator-Hero.png"}],"kind":"article","title":"Launch Control Playground","url":"\/documentation\/launchcontrol\/launchcontrolplayground","abstract":[{"type":"text","text":"Control UI elements live using Launchpad and MIDI in this LaunchControl sample app with visual feedback."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/launchcontrolplayground","type":"topic","role":"sampleCode"},"Midi-Grid-Animator-Hero.png":{"identifier":"Midi-Grid-Animator-Hero.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/com.soundform.LaunchControl\/Midi-Grid-Animator-Hero@1x.png"}],"alt":"Hero Image"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LaunchControlVersionNumber":{"url":"\/documentation\/launchcontrol\/launchcontrolversionnumber","title":"LaunchControlVersionNumber","role":"symbol","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LaunchControlVersionNumber","fragments":[{"kind":"identifier","text":"LaunchControlVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for LaunchControl."}],"kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midi"],"anchor":"Getting-Started"},{"generated":true,"title":"Articles","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/launchcontrolplayground","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/midigridanimator"],"anchor":"Articles"},{"generated":true,"title":"Variables","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LaunchControlVersionNumber","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LaunchControlVersionString"],"anchor":"Variables"},{"generated":true,"title":"Functions","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIWriteLog(_:_:_:_:_:)"],"anchor":"Functions"},{"generated":true,"title":"Macros","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDI_LOG"],"anchor":"Macros"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel"],"anchor":"Enumerations"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/title","value":"LCMIDILogLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/fragments","value":[{"text":"LCMIDILogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/navigatorTitle","value":[{"text":"LCMIDILogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIWriteLog(_:_:_:_:_:)\/title","value":"LCMIDIWriteLog","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIWriteLog(_:_:_:_:_:)\/fragments","value":[{"text":"LCMIDIWriteLog","kind":"identifier"}],"op":"replace"}]}]}