{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatal"}],"modules":[{"name":"LaunchControl"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","externalID":"c:@E@LCMIDILogLevel@LCMIDILogLevelFatal","navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevelFatal"}],"title":"LCMIDILogLevel.fatal"},"variants":[{"paths":["\/documentation\/launchcontrol\/lcmidiloglevel\/fatal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmidiloglevel\/fatal"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fatal","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/fatal","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel":{"url":"\/documentation\/launchcontrol\/lcmidiloglevel","title":"LCMIDILogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDILogLevel"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevel"}],"role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel","abstract":[],"type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/fatal":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/fatal","title":"LCMIDILogLevel.fatal","abstract":[],"url":"\/documentation\/launchcontrol\/lcmidiloglevel\/fatal","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fatal"}],"navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevelFatal"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"LCMIDILogLevelFatal"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"LCMIDILogLevelFatal"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"LCMIDILogLevelFatal","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/title","op":"replace","value":"LCMIDILogLevel"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"LCMIDILogLevel"}]},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/navigatorTitle","op":"replace","value":[{"text":"LCMIDILogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1fatal\/title","op":"replace","value":"LCMIDILogLevelFatal"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel~1fatal\/fragments","op":"replace","value":[{"text":"LCMIDILogLevelFatal","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}