{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"LaunchControl"}],"role":"collectionGroup"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmidiloglevel\/rawrepresentable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel"]]},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel":{"url":"\/documentation\/launchcontrol\/lcmidiloglevel","title":"LCMIDILogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LCMIDILogLevel"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LCMIDILogLevel"}],"role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel","abstract":[],"type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/hash(into:)":{"title":"hash(into:)","url":"\/documentation\/launchcontrol\/lcmidiloglevel\/hash(into:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/hash(into:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]}},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDILogLevel/hashValue":{"type":"topic","abstract":[],"kind":"symbol","title":"hashValue","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDILogLevel\/hashValue","url":"\/documentation\/launchcontrol\/lcmidiloglevel\/hashvalue","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"LCMIDILogLevel","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LCMIDILogLevel"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"LCMIDILogLevel"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDILogLevel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}