{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allMIDIDeviceNames"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":" instances representing the display names of available MIDI devices."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/allmididevicenames()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/allmididevicenames()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/allMIDIDeviceNames()"},"abstract":[{"type":"text","text":"Retrieves a combined list of all known MIDI device names, including both input and output endpoints."}],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"sections":[],"kind":"symbol","metadata":{"title":"allMIDIDeviceNames()","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allMIDIDeviceNames"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"allMIDIDeviceNames"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"LaunchControl"}],"externalID":"c:objc(cs)LCMIDIDeviceManager(im)allMIDIDeviceNames"},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/allMIDIDeviceNames()":{"kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/allMIDIDeviceNames()","role":"symbol","abstract":[{"text":"Retrieves a combined list of all known MIDI device names, including both input and output endpoints.","type":"text"}],"title":"allMIDIDeviceNames()","type":"topic","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/allmididevicenames()","navigatorTitle":[{"text":"allMIDIDeviceNames","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allMIDIDeviceNames","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"allMIDIDeviceNames","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"allMIDIDeviceNames","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"allMIDIDeviceNames","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":" instances representing the display names of available MIDI devices."}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"allMIDIDeviceNames","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1allMIDIDeviceNames()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1allMIDIDeviceNames()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"allMIDIDeviceNames","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}]}]}]}