{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forEndpoint","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"endpoint","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The endpoint reference to resolve."}],"type":"paragraph"}],"name":"endpoint"}]},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A string containing the device name, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no name could be determined.","type":"text"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"LaunchControl"}],"title":"deviceName(forEndpoint:)","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"deviceNameForEndpoint:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forEndpoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MIDIEndpointRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@MIDIEndpointRef"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)LCMIDIDeviceManager(im)deviceNameForEndpoint:","roleHeading":"Instance Method"},"abstract":[{"text":"Resolves the device name associated with a given MIDI endpoint reference.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/devicename(forendpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/devicename(forendpoint:)"]}],"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/deviceName(forEndpoint:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/deviceName(forEndpoint:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forEndpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MIDIEndpointRef","text":"MIDIEndpointRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceNameForEndpoint:"}],"role":"symbol","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/devicename(forendpoint:)","kind":"symbol","title":"deviceName(forEndpoint:)","abstract":[{"text":"Resolves the device name associated with a given MIDI endpoint reference.","type":"text"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/deviceName(forEndpoint:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"deviceNameForEndpoint:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deviceNameForEndpoint:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"deviceNameForEndpoint:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MIDIEndpointRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@MIDIEndpointRef"},{"text":") ","kind":"text"},{"text":"endpoint","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The endpoint reference to resolve.","type":"text"}]}],"name":"endpoint"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A string containing the device name, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no name could be determined."}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","op":"replace","value":"LCMIDIDeviceManager"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","op":"replace","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","op":"replace","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1deviceName(forEndpoint:)\/title","op":"replace","value":"deviceNameForEndpoint:"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1deviceName(forEndpoint:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deviceNameForEndpoint:"}]}]}]}