{"sections":[],"abstract":[{"text":"Disables debug output previously enabled with ","type":"text"},{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","isActive":true,"type":"reference"},{"text":".","type":"text"}],"metadata":{"externalID":"c:objc(cs)LCMIDIDeviceManager(im)disableDebugLogging","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableDebugLogging"},{"kind":"text","text":"()"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"disableDebugLogging"}],"role":"symbol","modules":[{"name":"LaunchControl"}],"title":"disableDebugLogging()"},"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"variants":[{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/disabledebuglogging()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/disabledebuglogging()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/disableDebugLogging()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableDebugLogging","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/enableDebugLogging()":{"role":"symbol","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/enabledebuglogging()","title":"enableDebugLogging()","navigatorTitle":[{"kind":"identifier","text":"enableDebugLogging"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDebugLogging"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","kind":"symbol","abstract":[{"type":"text","text":"Enables debug output for MIDI message transmission and reception to assist with development and troubleshooting."}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/disableDebugLogging()":{"navigatorTitle":[{"kind":"identifier","text":"disableDebugLogging"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableDebugLogging"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/disableDebugLogging()","type":"topic","abstract":[{"type":"text","text":"Disables debug output previously enabled with "},{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/enableDebugLogging()","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"disableDebugLogging()","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/disabledebuglogging()","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"disableDebugLogging","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableDebugLogging","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableDebugLogging"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"LCMIDIDeviceManager","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle"},{"op":"replace","value":"enableDebugLogging","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1enableDebugLogging()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableDebugLogging"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1enableDebugLogging()\/fragments"},{"op":"replace","value":"disableDebugLogging","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1disableDebugLogging()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableDebugLogging"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1disableDebugLogging()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}