{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ofOutputDeviceNamed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"deviceName","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output device name to search for."}]}],"name":"deviceName"}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A valid index if the device is found, or "},{"code":"-1","type":"codeVoice"},{"type":"text","text":" if it is not present in the list."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/index(ofoutputdevicenamed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/index(ofoutputdevicenamed:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/index(ofOutputDeviceNamed:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"indexOfOutputDeviceNamed:","kind":"identifier"}],"modules":[{"name":"LaunchControl"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofOutputDeviceNamed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"externalID":"c:objc(cs)LCMIDIDeviceManager(im)indexOfOutputDeviceNamed:","role":"symbol","title":"index(ofOutputDeviceNamed:)"},"abstract":[{"text":"Returns the index of a named output device within the internal output device list.","type":"text"}],"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/index(ofOutputDeviceNamed:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/index(ofOutputDeviceNamed:)","abstract":[{"text":"Returns the index of a named output device within the internal output device list.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfOutputDeviceNamed:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofOutputDeviceNamed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"index(ofOutputDeviceNamed:)","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/index(ofoutputdevicenamed:)"},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"indexOfOutputDeviceNamed:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfOutputDeviceNamed:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"indexOfOutputDeviceNamed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceName"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"deviceName","content":[{"type":"paragraph","inlineContent":[{"text":"The output device name to search for.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A valid index if the device is found, or "},{"type":"codeVoice","code":"-1"},{"type":"text","text":" if it is not present in the list."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"LCMIDIDeviceManager","op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title"},{"value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments"},{"value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle"},{"value":"indexOfOutputDeviceNamed:","op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1index(ofOutputDeviceNamed:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfOutputDeviceNamed:"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1index(ofOutputDeviceNamed:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}