{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/init(clientname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/init(clientname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Creates and configures a new instance of the MIDI device manager with a client name to register with CoreMIDI."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The client name used to identify this MIDI session with the system."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", a default name is generated internally."}],"type":"paragraph"}],"name":"clientName"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/init(clientName:)"},"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"role":"symbol","externalID":"c:objc(cs)LCMIDIDeviceManager(im)initWithClientName:","roleHeading":"Initializer","title":"init(clientName:)","modules":[{"name":"LaunchControl"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithClientName:"}]},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/init(clientName:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithClientName:"}],"abstract":[{"type":"text","text":"Creates and configures a new instance of the MIDI device manager with a client name to register with CoreMIDI."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(clientName:)","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/init(clientname:)","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/init(clientName:)","kind":"symbol","type":"topic"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithClientName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithClientName:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithClientName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"clientName","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The client name used to identify this MIDI session with the system."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", a default name is generated internally."}],"type":"paragraph"}],"name":"clientName"}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A new instance of "},{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","isActive":true,"type":"reference"},{"type":"text","text":" ready for use."}],"type":"paragraph"}]},"op":"add"},{"value":"initWithClientName:","op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1init(clientName:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithClientName:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1init(clientName:)\/fragments"},{"value":"LCMIDIDeviceManager","op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title"},{"value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments"},{"value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle"}]}]}