{"kind":"symbol","variants":[{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/isdeviceavailable(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/isdeviceavailable(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Checks whether a specific output device is currently available by name."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"LaunchControl"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeviceAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isDeviceAvailable:"}],"symbolKind":"method","title":"isDeviceAvailable(_:)","externalID":"c:objc(cs)LCMIDIDeviceManager(im)isDeviceAvailable:","roleHeading":"Instance Method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/isDeviceAvailable(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeviceAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"deviceName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The exact name of the output device to verify."}],"type":"paragraph"}],"name":"deviceName"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the device is currently available and active; otherwise, "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}]}],"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/isDeviceAvailable(_:)":{"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/isDeviceAvailable(_:)","title":"isDeviceAvailable(_:)","kind":"symbol","type":"topic","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/isdeviceavailable(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeviceAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isDeviceAvailable:"}],"abstract":[{"type":"text","text":"Checks whether a specific output device is currently available by name."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isDeviceAvailable:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isDeviceAvailable:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isDeviceAvailable:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceName"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The exact name of the output device to verify.","type":"text"}]}],"name":"deviceName"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the device is currently available and active; otherwise, "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}},{"value":"LCMIDIDeviceManager","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","op":"replace"},{"value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","op":"replace"},{"value":"isDeviceAvailable:","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1isDeviceAvailable(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isDeviceAvailable:"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1isDeviceAvailable(_:)\/fragments","op":"replace"}]}]}