{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxMIDIPacketDataSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/maxMIDIPacketDataSize"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/maxmidipacketdatasize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/maxmidipacketdatasize"]}],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"abstract":[{"type":"text","text":"Maximum allowed size in bytes for a single MIDI packet data message."},{"type":"text","text":" "},{"type":"text","text":"Messages larger than this will be rejected and logged as warnings."},{"type":"text","text":" "},{"type":"text","text":"Default is 4096 bytes."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"maxMIDIPacketDataSize"}],"title":"maxMIDIPacketDataSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMIDIPacketDataSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"modules":[{"name":"LaunchControl"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)LCMIDIDeviceManager(py)maxMIDIPacketDataSize","role":"symbol"},"sections":[],"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/maxMIDIPacketDataSize":{"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/maxmidipacketdatasize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMIDIPacketDataSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"maxMIDIPacketDataSize","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/maxMIDIPacketDataSize","abstract":[{"type":"text","text":"Maximum allowed size in bytes for a single MIDI packet data message."},{"type":"text","text":" "},{"type":"text","text":"Messages larger than this will be rejected and logged as warnings."},{"type":"text","text":" "},{"type":"text","text":"Default is 4096 bytes."}],"navigatorTitle":[{"kind":"identifier","text":"maxMIDIPacketDataSize"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"maxMIDIPacketDataSize","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"maxMIDIPacketDataSize","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"size_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@size_t"},{"text":" ","kind":"text"},{"text":"maxMIDIPacketDataSize","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"LCMIDIDeviceManager","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","op":"replace"},{"value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","op":"replace"},{"value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","op":"replace"},{"value":"maxMIDIPacketDataSize","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1maxMIDIPacketDataSize\/title","op":"replace"},{"value":[{"text":"maxMIDIPacketDataSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1maxMIDIPacketDataSize\/fragments","op":"replace"}]}]}