{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputEndpoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDeviceNamed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"deviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"deviceName","content":[{"inlineContent":[{"text":"The exact name of the output device.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A "},{"code":"MIDIEndpointRef","type":"codeVoice"},{"type":"text","text":" representing the endpoint associated with the device, or "},{"code":"NULL","type":"codeVoice"},{"type":"text","text":" if unavailable."}],"type":"paragraph"}]}],"abstract":[{"text":"Resolves the specified output device name to a ","type":"text"},{"type":"codeVoice","code":"MIDIEndpointRef"},{"text":" that can be used for direct transmission.","type":"text"}],"metadata":{"externalID":"c:objc(cs)LCMIDIDeviceManager(im)outputEndpointForDeviceNamed:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"outputEndpointForDeviceNamed:"}],"title":"outputEndpoint(forDeviceNamed:)","symbolKind":"method","modules":[{"name":"LaunchControl"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputEndpoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDeviceNamed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef"}]},"variants":[{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/outputendpoint(fordevicenamed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/outputendpoint(fordevicenamed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/outputEndpoint(forDeviceNamed:)","interfaceLanguage":"swift"},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/outputEndpoint(forDeviceNamed:)":{"role":"symbol","kind":"symbol","title":"outputEndpoint(forDeviceNamed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputEndpoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDeviceNamed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef"}],"navigatorTitle":[{"kind":"identifier","text":"outputEndpointForDeviceNamed:"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/outputEndpoint(forDeviceNamed:)","type":"topic","abstract":[{"type":"text","text":"Resolves the specified output device name to a "},{"code":"MIDIEndpointRef","type":"codeVoice"},{"type":"text","text":" that can be used for direct transmission."}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/outputendpoint(fordevicenamed:)"},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"outputEndpointForDeviceNamed:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"outputEndpointForDeviceNamed:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@MIDIEndpointRef","text":"MIDIEndpointRef","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"outputEndpointForDeviceNamed:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceName","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The exact name of the output device.","type":"text"}],"type":"paragraph"}],"name":"deviceName"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MIDIEndpointRef"},{"type":"text","text":" representing the endpoint associated with the device, or "},{"type":"codeVoice","code":"NULL"},{"type":"text","text":" if unavailable."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1outputEndpoint(forDeviceNamed:)\/title","value":"outputEndpointForDeviceNamed:"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1outputEndpoint(forDeviceNamed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"outputEndpointForDeviceNamed:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","op":"replace","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}