{"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/rescandevices()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/rescandevices()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Manually initiates a device rescan to refresh the list of available endpoints.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rescanDevices","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is useful when hardware devices are connected or disconnected and automatic CoreMIDI"},{"type":"text","text":" "},{"type":"text","text":"notifications are insufficient or delayed."}]}]}],"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/rescanDevices()","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"rescanDevices()","modules":[{"name":"LaunchControl"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rescanDevices"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)LCMIDIDeviceManager(im)rescanDevices","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"rescanDevices"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/rescanDevices()":{"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/rescandevices()","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/rescanDevices()","title":"rescanDevices()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rescanDevices"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rescanDevices"}],"abstract":[{"type":"text","text":"Manually initiates a device rescan to refresh the list of available endpoints."}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rescanDevices","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rescanDevices"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rescanDevices","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"rescanDevices","op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1rescanDevices()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rescanDevices","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1rescanDevices()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]}]}]}