{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"sendData:toEndpoint:","kind":"identifier"}],"modules":[{"name":"LaunchControl"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toEndpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)LCMIDIDeviceManager(im)sendData:toEndpoint:","title":"send(_:toEndpoint:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/send(_:toendpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/send(_:toendpoint:)"]}],"abstract":[{"type":"text","text":"Sends a MIDI message directly to the specified CoreMIDI output endpoint."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toEndpoint","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"endpoint","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"data","content":[{"inlineContent":[{"type":"text","text":"A binary data object containing a complete MIDI message."}],"type":"paragraph"}]},{"name":"endpoint","content":[{"type":"paragraph","inlineContent":[{"text":"A valid ","type":"text"},{"code":"MIDIEndpointRef","type":"codeVoice"},{"text":" corresponding to an output destination.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"name":"Warning","type":"aside","style":"warning","content":[{"type":"paragraph","inlineContent":[{"text":"This method bypasses the device name abstraction and sends raw data directly to the specified endpoint.","type":"text"},{"text":" ","type":"text"},{"text":"The caller is responsible for ensuring that the endpoint is valid and operational.","type":"text"}]}]}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toEndpoint:)"},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/send(_:toEndpoint:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toEndpoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@MIDIEndpointRef","text":"MIDIEndpointRef","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"sendData:toEndpoint:","kind":"identifier"}],"title":"send(_:toEndpoint:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/send(_:toEndpoint:)","abstract":[{"text":"Sends a MIDI message directly to the specified CoreMIDI output endpoint.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/send(_:toendpoint:)"},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"sendData:toEndpoint:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendData:toEndpoint:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sendData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toEndpoint:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MIDIEndpointRef","preciseIdentifier":"c:@T@MIDIEndpointRef","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"endpoint","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"text":"A binary data object containing a complete MIDI message.","type":"text"}]}]},{"name":"endpoint","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A valid "},{"code":"MIDIEndpointRef","type":"codeVoice"},{"type":"text","text":" corresponding to an output destination."}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1send(_:toEndpoint:)\/title","value":"sendData:toEndpoint:","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1send(_:toEndpoint:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendData:toEndpoint:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}