{"kind":"symbol","variants":[{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/setdispatchqueue(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/setdispatchqueue(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Specifies the dispatch queue on which the input handler block should execute."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDispatchQueue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"LaunchControl"}],"role":"symbol","externalID":"c:objc(cs)LCMIDIDeviceManager(im)setDispatchQueue:","navigatorTitle":[{"text":"setDispatchQueue:","kind":"identifier"}],"title":"setDispatchQueue(_:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDispatchQueue(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDispatchQueue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"queue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"dispatch_queue_t"},{"type":"text","text":" instance that will receive the input handler invocations."}]}],"name":"queue"}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"If not explicitly set, messages are delivered on the main queue. This method allows fine-grained","type":"text"},{"text":" ","type":"text"},{"text":"control over concurrency and execution context.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The default queue is the main queue if this method is not called.","type":"text"}]}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/setDispatchQueue(_:)":{"url":"\/documentation\/launchcontrol\/lcmididevicemanager\/setdispatchqueue(_:)","navigatorTitle":[{"kind":"identifier","text":"setDispatchQueue:"}],"type":"topic","title":"setDispatchQueue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDispatchQueue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setDispatchQueue(_:)","role":"symbol","abstract":[{"type":"text","text":"Specifies the dispatch queue on which the input handler block should execute."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setDispatchQueue:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDispatchQueue:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDispatchQueue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"queue"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A "},{"code":"dispatch_queue_t","type":"codeVoice"},{"type":"text","text":" instance that will receive the input handler invocations."}],"type":"paragraph"}],"name":"queue"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"LCMIDIDeviceManager","op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"kind":"identifier","text":"LCMIDIDeviceManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setDispatchQueue(_:)\/title","value":"setDispatchQueue:","op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setDispatchQueue(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDispatchQueue:"}]}]}]}