{"hierarchy":{"paths":[["doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxMIDIPacketDataSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"maxSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"maxSize","content":[{"type":"paragraph","inlineContent":[{"text":"The new maximum packet data size in bytes.","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"text":"Sets the maximum allowed size in bytes for a single MIDI packet data message.","type":"text"},{"text":" ","type":"text"},{"text":"Messages larger than this will be rejected and logged as warnings.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setMaxMIDIPacketDataSize:"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxMIDIPacketDataSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"modules":[{"name":"LaunchControl"}],"title":"setMaxMIDIPacketDataSize(_:)","externalID":"c:objc(cs)LCMIDIDeviceManager(im)setMaxMIDIPacketDataSize:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/setmaxmidipacketdatasize(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/launchcontrol\/lcmididevicemanager\/setmaxmidipacketdatasize(_:)"]}],"identifier":{"url":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setMaxMIDIPacketDataSize(_:)","interfaceLanguage":"swift"},"references":{"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager/setMaxMIDIPacketDataSize(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setMaxMIDIPacketDataSize:"}],"type":"topic","abstract":[{"type":"text","text":"Sets the maximum allowed size in bytes for a single MIDI packet data message."},{"type":"text","text":" "},{"type":"text","text":"Messages larger than this will be rejected and logged as warnings."}],"identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager\/setMaxMIDIPacketDataSize(_:)","url":"\/documentation\/launchcontrol\/lcmididevicemanager\/setmaxmidipacketdatasize(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxMIDIPacketDataSize"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"setMaxMIDIPacketDataSize(_:)","kind":"symbol"},"doc://com.soundform.LaunchControl/documentation/LaunchControl/LCMIDIDeviceManager":{"abstract":[{"text":"A MIDI device manager based on CoreMIDI, designed to facilitate communication with connected MIDI hardware.","type":"text"}],"url":"\/documentation\/launchcontrol\/lcmididevicemanager","role":"symbol","type":"topic","kind":"symbol","title":"LCMIDIDeviceManager","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl\/LCMIDIDeviceManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LCMIDIDeviceManager","kind":"identifier"}],"navigatorTitle":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},"doc://com.soundform.LaunchControl/documentation/LaunchControl":{"url":"\/documentation\/launchcontrol","role":"collection","abstract":[{"type":"text","text":"A robust CoreMIDI-based framework for communicating with Launchpad and other MIDI hardware on Apple platforms."}],"title":"LaunchControl","type":"topic","identifier":"doc:\/\/com.soundform.LaunchControl\/documentation\/LaunchControl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMaxMIDIPacketDataSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMaxMIDIPacketDataSize:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setMaxMIDIPacketDataSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@size_t"},{"text":") ","kind":"text"},{"text":"maxSize","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"maxSize","content":[{"inlineContent":[{"type":"text","text":"The new maximum packet data size in bytes."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setMaxMIDIPacketDataSize(_:)\/title","value":"setMaxMIDIPacketDataSize:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager~1setMaxMIDIPacketDataSize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMaxMIDIPacketDataSize:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/title","value":"LCMIDIDeviceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/fragments","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.soundform.LaunchControl~1documentation~1LaunchControl~1LCMIDIDeviceManager\/navigatorTitle","value":[{"text":"LCMIDIDeviceManager","kind":"identifier"}]}]}]}